# Build stage
FROM golang:1.25.1-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o scrapper ./cmd/scrapper

# Final stage
FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/scrapper .

EXPOSE 8080 50051

CMD ["./scrapper"]
