// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

type ScrapperServiceClient interface {
	RegisterChat(ctx context.Context, in *RegisterChatRequest, opts ...grpc.CallOption) (*RegisterChatResponse, error)
	UnregisterChat(ctx context.Context, in *UnregisterChatRequest, opts ...grpc.CallOption) (*UnregisterChatResponse, error)
	AddLink(ctx context.Context, in *AddLinkRequest, opts ...grpc.CallOption) (*AddLinkResponse, error)
	RemoveLink(ctx context.Context, in *RemoveLinkRequest, opts ...grpc.CallOption) (*RemoveLinkResponse, error)
	GetLinks(ctx context.Context, in *GetLinksRequest, opts ...grpc.CallOption) (*GetLinksResponse, error)
}

type scrapperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScrapperServiceClient(cc grpc.ClientConnInterface) ScrapperServiceClient {
	return &scrapperServiceClient{cc}
}

func (c *scrapperServiceClient) RegisterChat(ctx context.Context, in *RegisterChatRequest, opts ...grpc.CallOption) (*RegisterChatResponse, error) {
	out := new(RegisterChatResponse)
	err := c.cc.Invoke(ctx, "/scrapper.ScrapperService/RegisterChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scrapperServiceClient) UnregisterChat(ctx context.Context, in *UnregisterChatRequest, opts ...grpc.CallOption) (*UnregisterChatResponse, error) {
	out := new(UnregisterChatResponse)
	err := c.cc.Invoke(ctx, "/scrapper.ScrapperService/UnregisterChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scrapperServiceClient) AddLink(ctx context.Context, in *AddLinkRequest, opts ...grpc.CallOption) (*AddLinkResponse, error) {
	out := new(AddLinkResponse)
	err := c.cc.Invoke(ctx, "/scrapper.ScrapperService/AddLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scrapperServiceClient) RemoveLink(ctx context.Context, in *RemoveLinkRequest, opts ...grpc.CallOption) (*RemoveLinkResponse, error) {
	out := new(RemoveLinkResponse)
	err := c.cc.Invoke(ctx, "/scrapper.ScrapperService/RemoveLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scrapperServiceClient) GetLinks(ctx context.Context, in *GetLinksRequest, opts ...grpc.CallOption) (*GetLinksResponse, error) {
	out := new(GetLinksResponse)
	err := c.cc.Invoke(ctx, "/scrapper.ScrapperService/GetLinks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type ScrapperServiceServer interface {
	RegisterChat(context.Context, *RegisterChatRequest) (*RegisterChatResponse, error)
	UnregisterChat(context.Context, *UnregisterChatRequest) (*UnregisterChatResponse, error)
	AddLink(context.Context, *AddLinkRequest) (*AddLinkResponse, error)
	RemoveLink(context.Context, *RemoveLinkRequest) (*RemoveLinkResponse, error)
	GetLinks(context.Context, *GetLinksRequest) (*GetLinksResponse, error)
	mustEmbedUnimplementedScrapperServiceServer()
}

type UnimplementedScrapperServiceServer struct {
}

func (UnimplementedScrapperServiceServer) RegisterChat(context.Context, *RegisterChatRequest) (*RegisterChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterChat not implemented")
}
func (UnimplementedScrapperServiceServer) UnregisterChat(context.Context, *UnregisterChatRequest) (*UnregisterChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterChat not implemented")
}
func (UnimplementedScrapperServiceServer) AddLink(context.Context, *AddLinkRequest) (*AddLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLink not implemented")
}
func (UnimplementedScrapperServiceServer) RemoveLink(context.Context, *RemoveLinkRequest) (*RemoveLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveLink not implemented")
}
func (UnimplementedScrapperServiceServer) GetLinks(context.Context, *GetLinksRequest) (*GetLinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLinks not implemented")
}
func (UnimplementedScrapperServiceServer) mustEmbedUnimplementedScrapperServiceServer() {}

type UnsafeScrapperServiceServer interface {
	mustEmbedUnsafeScrapperServiceServer()
}

func RegisterScrapperServiceServer(s grpc.ServiceRegistrar, srv ScrapperServiceServer) {
	s.RegisterService(&ScrapperService_ServiceDesc, srv)
}

func _ScrapperService_RegisterChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperServiceServer).RegisterChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scrapper.ScrapperService/RegisterChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperServiceServer).RegisterChat(ctx, req.(*RegisterChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScrapperService_UnregisterChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperServiceServer).UnregisterChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scrapper.ScrapperService/UnregisterChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperServiceServer).UnregisterChat(ctx, req.(*UnregisterChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScrapperService_AddLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperServiceServer).AddLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scrapper.ScrapperService/AddLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperServiceServer).AddLink(ctx, req.(*AddLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScrapperService_RemoveLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperServiceServer).RemoveLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scrapper.ScrapperService/RemoveLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperServiceServer).RemoveLink(ctx, req.(*RemoveLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScrapperService_GetLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperServiceServer).GetLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scrapper.ScrapperService/GetLinks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperServiceServer).GetLinks(ctx, req.(*GetLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var ScrapperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scrapper.ScrapperService",
	HandlerType: (*ScrapperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterChat",
			Handler:    _ScrapperService_RegisterChat_Handler,
		},
		{
			MethodName: "UnregisterChat",
			Handler:    _ScrapperService_UnregisterChat_Handler,
		},
		{
			MethodName: "AddLink",
			Handler:    _ScrapperService_AddLink_Handler,
		},
		{
			MethodName: "RemoveLink",
			Handler:    _ScrapperService_RemoveLink_Handler,
		},
		{
			MethodName: "GetLinks",
			Handler:    _ScrapperService_GetLinks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scrapper.proto",
}
