// Code generated by protoc-gen-go. DO NOT EDIT.

package grpc

type RegisterChatRequest struct {
	ChatId int64
}

type RegisterChatResponse struct {
	Success bool
}

type UnregisterChatRequest struct {
	ChatId int64
}

type UnregisterChatResponse struct {
	Success bool
}

type AddLinkRequest struct {
	ChatId  int64
	Link    string
	Tags    []string
	Filters []string
}

type AddLinkResponse struct {
	Id      int64
	Url     string
	Tags    []string
	Filters []string
}

type RemoveLinkRequest struct {
	ChatId int64
	Link   string
}

type RemoveLinkResponse struct {
	Url string
}

type GetLinksRequest struct {
	ChatId int64
	Tag    string
}

type LinkData struct {
	Id      int64
	Url     string
	Tags    []string
	Filters []string
}

type GetLinksResponse struct {
	Links []*LinkData
	Size  int32
}
